
    create table cliente (
       id int8 generated by default as identity,
        email varchar(255),
        nome varchar(255),
        senha varchar(255),
        primary key (id)
    );

    create table cliente_perfis (
       cliente_id int8 not null,
        perfis_id int8 not null
    );

    create table perfil (
       id int8 generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table transacoes (
       id int8 generated by default as identity,
        categoria int4,
        conta int4,
        data_do_lancamento date,
        descricao varchar(255),
        tipo int4,
        valor_transacao numeric(19, 2),
        cliente_id int8,
        primary key (id)
    );

    alter table if exists cliente_perfis 
       add constraint FK2x9a3roc19iso4trosqx9cn4c 
       foreign key (perfis_id) 
       references perfil;

    alter table if exists cliente_perfis 
       add constraint FKow5p279172nbtvd8m6n0y2ay6 
       foreign key (cliente_id) 
       references cliente;

    alter table if exists transacoes 
       add constraint FK2rxrhbl861ul4utawv56o0vh8 
       foreign key (cliente_id) 
       references cliente;
